<?php

/**
 * Nuevoingreso2018 filter form base class.
 *
 * @package    preinscripcion
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseNuevoingreso2018FormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                   => new sfWidgetFormFilterInput(),
      'tipo_identificacion'  => new sfWidgetFormFilterInput(),
      'identificacion'       => new sfWidgetFormFilterInput(),
      'primer_nombre'        => new sfWidgetFormFilterInput(),
      'segundo_nombre'       => new sfWidgetFormFilterInput(),
      'primer_apellido'      => new sfWidgetFormFilterInput(),
      'segundo_apellido'     => new sfWidgetFormFilterInput(),
      'sexo_id'              => new sfWidgetFormFilterInput(),
      'fecha_nacimiento'     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'pais_origen_id'       => new sfWidgetFormFilterInput(),
      'estado_id'            => new sfWidgetFormFilterInput(),
      'municipio_id'         => new sfWidgetFormFilterInput(),
      'parroquia_id'         => new sfWidgetFormFilterInput(),
      'direccion'            => new sfWidgetFormFilterInput(),
      'punto_referencia'     => new sfWidgetFormFilterInput(),
      'asic_estado_id'       => new sfWidgetFormFilterInput(),
      'asic_municipio_id'    => new sfWidgetFormFilterInput(),
      'asic_id'              => new sfWidgetFormFilterInput(),
      'telefono'             => new sfWidgetFormFilterInput(),
      'telefono_casa'        => new sfWidgetFormFilterInput(),
      'correo_electronico'   => new sfWidgetFormFilterInput(),
      'persona_contacto'     => new sfWidgetFormFilterInput(),
      'estado_civil_id'      => new sfWidgetFormFilterInput(),
      'n_hijos'              => new sfWidgetFormFilterInput(),
      'ano_curso'            => new sfWidgetFormFilterInput(),
      'cohorte'              => new sfWidgetFormFilterInput(),
      'etnia_indigena_id'    => new sfWidgetFormFilterInput(),
      'elam'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'idmatricula'          => new sfWidgetFormFilterInput(),
      'trabaja'              => new sfWidgetFormFilterInput(),
      'lugar'                => new sfWidgetFormFilterInput(),
      'horario'              => new sfWidgetFormFilterInput(),
      'ingresos'             => new sfWidgetFormFilterInput(),
      'telefono_trabajo'     => new sfWidgetFormFilterInput(),
      'centro_poblado_id'    => new sfWidgetFormFilterInput(),
      'foto'                 => new sfWidgetFormFilterInput(),
      'tipo_empresa'         => new sfWidgetFormFilterInput(),
      'estatus'              => new sfWidgetFormFilterInput(),
      'banco'                => new sfWidgetFormFilterInput(),
      'tipo_cuenta'          => new sfWidgetFormFilterInput(),
      'cuenta'               => new sfWidgetFormFilterInput(),
      'cta_social'           => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'cta_personal'         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'no_cta'               => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'n_ingreso'            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'opsu'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'postulado'            => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'registro'             => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'verificado'           => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fecha_verificacion'   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'notas'                => new sfWidgetFormFilterInput(),
      'pnf'                  => new sfWidgetFormFilterInput(),
      'codigo_tlf_id'        => new sfWidgetFormFilterInput(),
      'codigo_tlf_casa_id'   => new sfWidgetFormFilterInput(),
      'parentesco'           => new sfWidgetFormFilterInput(),
      'codigo_tlf_contacto'  => new sfWidgetFormFilterInput(),
      'telefono_contacto'    => new sfWidgetFormFilterInput(),
      'situacion_academica'  => new sfWidgetFormFilterInput(),
      'carnet_patria'        => new sfWidgetFormFilterInput(),
      'serial_carnet_patria' => new sfWidgetFormFilterInput(),
      'dedicacion_laboral'   => new sfWidgetFormFilterInput(),
      'lgbt'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'afrodescendiente'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'asic_parroquia_id'    => new sfWidgetFormFilterInput(),
      'asic_hab_id'          => new sfWidgetFormFilterInput(),
      'mod_ingreso_id'       => new sfWidgetFormFilterInput(),
      'convocatoria'         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
    ));

    $this->setValidators(array(
      'id'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tipo_identificacion'  => new sfValidatorPass(array('required' => false)),
      'identificacion'       => new sfValidatorPass(array('required' => false)),
      'primer_nombre'        => new sfValidatorPass(array('required' => false)),
      'segundo_nombre'       => new sfValidatorPass(array('required' => false)),
      'primer_apellido'      => new sfValidatorPass(array('required' => false)),
      'segundo_apellido'     => new sfValidatorPass(array('required' => false)),
      'sexo_id'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fecha_nacimiento'     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'pais_origen_id'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'estado_id'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'municipio_id'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'parroquia_id'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'direccion'            => new sfValidatorPass(array('required' => false)),
      'punto_referencia'     => new sfValidatorPass(array('required' => false)),
      'asic_estado_id'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asic_municipio_id'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asic_id'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'telefono'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'telefono_casa'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'correo_electronico'   => new sfValidatorPass(array('required' => false)),
      'persona_contacto'     => new sfValidatorPass(array('required' => false)),
      'estado_civil_id'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'n_hijos'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'ano_curso'            => new sfValidatorPass(array('required' => false)),
      'cohorte'              => new sfValidatorPass(array('required' => false)),
      'etnia_indigena_id'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'elam'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'idmatricula'          => new sfValidatorPass(array('required' => false)),
      'trabaja'              => new sfValidatorPass(array('required' => false)),
      'lugar'                => new sfValidatorPass(array('required' => false)),
      'horario'              => new sfValidatorPass(array('required' => false)),
      'ingresos'             => new sfValidatorPass(array('required' => false)),
      'telefono_trabajo'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'centro_poblado_id'    => new sfValidatorPass(array('required' => false)),
      'foto'                 => new sfValidatorPass(array('required' => false)),
      'tipo_empresa'         => new sfValidatorPass(array('required' => false)),
      'estatus'              => new sfValidatorPass(array('required' => false)),
      'banco'                => new sfValidatorPass(array('required' => false)),
      'tipo_cuenta'          => new sfValidatorPass(array('required' => false)),
      'cuenta'               => new sfValidatorPass(array('required' => false)),
      'cta_social'           => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'cta_personal'         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'no_cta'               => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'n_ingreso'            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'opsu'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'postulado'            => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'registro'             => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'verificado'           => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fecha_verificacion'   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'notas'                => new sfValidatorPass(array('required' => false)),
      'pnf'                  => new sfValidatorPass(array('required' => false)),
      'codigo_tlf_id'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'codigo_tlf_casa_id'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'parentesco'           => new sfValidatorPass(array('required' => false)),
      'codigo_tlf_contacto'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'telefono_contacto'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'situacion_academica'  => new sfValidatorPass(array('required' => false)),
      'carnet_patria'        => new sfValidatorPass(array('required' => false)),
      'serial_carnet_patria' => new sfValidatorPass(array('required' => false)),
      'dedicacion_laboral'   => new sfValidatorPass(array('required' => false)),
      'lgbt'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'afrodescendiente'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'asic_parroquia_id'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asic_hab_id'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mod_ingreso_id'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'convocatoria'         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
    ));

    $this->widgetSchema->setNameFormat('nuevoingreso2018_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Nuevoingreso2018';
  }

  public function getFields()
  {
    return array(
      'id'                   => 'Number',
      'tipo_identificacion'  => 'Text',
      'identificacion'       => 'Text',
      'primer_nombre'        => 'Text',
      'segundo_nombre'       => 'Text',
      'primer_apellido'      => 'Text',
      'segundo_apellido'     => 'Text',
      'sexo_id'              => 'Number',
      'fecha_nacimiento'     => 'Date',
      'pais_origen_id'       => 'Number',
      'estado_id'            => 'Number',
      'municipio_id'         => 'Number',
      'parroquia_id'         => 'Number',
      'direccion'            => 'Text',
      'punto_referencia'     => 'Text',
      'asic_estado_id'       => 'Number',
      'asic_municipio_id'    => 'Number',
      'asic_id'              => 'Number',
      'telefono'             => 'Number',
      'telefono_casa'        => 'Number',
      'correo_electronico'   => 'Text',
      'persona_contacto'     => 'Text',
      'estado_civil_id'      => 'Number',
      'n_hijos'              => 'Number',
      'ano_curso'            => 'Text',
      'cohorte'              => 'Text',
      'etnia_indigena_id'    => 'Number',
      'elam'                 => 'Boolean',
      'idmatricula'          => 'Text',
      'trabaja'              => 'Text',
      'lugar'                => 'Text',
      'horario'              => 'Text',
      'ingresos'             => 'Text',
      'telefono_trabajo'     => 'Number',
      'centro_poblado_id'    => 'Text',
      'foto'                 => 'Text',
      'tipo_empresa'         => 'Text',
      'estatus'              => 'Text',
      'banco'                => 'Text',
      'tipo_cuenta'          => 'Text',
      'cuenta'               => 'Text',
      'cta_social'           => 'Boolean',
      'cta_personal'         => 'Boolean',
      'no_cta'               => 'Boolean',
      'n_ingreso'            => 'Boolean',
      'opsu'                 => 'Boolean',
      'postulado'            => 'Boolean',
      'registro'             => 'Date',
      'verificado'           => 'Boolean',
      'fecha_verificacion'   => 'Date',
      'notas'                => 'Text',
      'pnf'                  => 'Text',
      'codigo_tlf_id'        => 'Number',
      'codigo_tlf_casa_id'   => 'Number',
      'parentesco'           => 'Text',
      'codigo_tlf_contacto'  => 'Number',
      'telefono_contacto'    => 'Number',
      'situacion_academica'  => 'Text',
      'carnet_patria'        => 'Text',
      'serial_carnet_patria' => 'Text',
      'dedicacion_laboral'   => 'Text',
      'lgbt'                 => 'Boolean',
      'afrodescendiente'     => 'Boolean',
      'asic_parroquia_id'    => 'Number',
      'asic_hab_id'          => 'Number',
      'mod_ingreso_id'       => 'Number',
      'convocatoria'         => 'Boolean',
    );
  }
}
