generator:
  class: sfDoctrineGenerator
  param:
    model_class:           preinscripcionCurso
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          preinscripcion_curso
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
      fields:  ~
      list:    
          batch_actions: {}
          object_actions: {}
          display: [nacionalidad, identificacion,pnombre,papellido,estado,pnf]
      filter:  
          display: [nacionalidad, identificacion,pnombre,papellido,estado_id,pnf_id]
      form:    ~
      edit:    ~
      new:     ~
