<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Actualizar', 'doctrine');

/**
 * BaseActualizar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tipo
 * @property string $identidad
 * @property string $nombre_1
 * @property string $apellido_1
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getTipo()       Returns the current record's "tipo" value
 * @method string     getIdentidad()  Returns the current record's "identidad" value
 * @method string     getNombre1()    Returns the current record's "nombre_1" value
 * @method string     getApellido1()  Returns the current record's "apellido_1" value
 * @method Actualizar setId()         Sets the current record's "id" value
 * @method Actualizar setTipo()       Sets the current record's "tipo" value
 * @method Actualizar setIdentidad()  Sets the current record's "identidad" value
 * @method Actualizar setNombre1()    Sets the current record's "nombre_1" value
 * @method Actualizar setApellido1()  Sets the current record's "apellido_1" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActualizar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actualizar');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'sequence' => 'actualizar_id',
             'length' => 4,
             ));
        $this->hasColumn('tipo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('identidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nombre_1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido_1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}