<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Graduandos8', 'doctrine');

/**
 * BaseGraduandos8
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $n
 * @property string $tipo_doc
 * @property string $doc_iden
 * @property string $ape1
 * @property string $ape2
 * @property string $nombres
 * @property string $gene
 * @property string $pais_o
 * @property string $estado
 * @property string $municipio
 * @property string $parr
 * @property string $asic
 * @property string $cohorte
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method string      getN()         Returns the current record's "n" value
 * @method string      getTipoDoc()   Returns the current record's "tipo_doc" value
 * @method string      getDocIden()   Returns the current record's "doc_iden" value
 * @method string      getApe1()      Returns the current record's "ape1" value
 * @method string      getApe2()      Returns the current record's "ape2" value
 * @method string      getNombres()   Returns the current record's "nombres" value
 * @method string      getGene()      Returns the current record's "gene" value
 * @method string      getPaisO()     Returns the current record's "pais_o" value
 * @method string      getEstado()    Returns the current record's "estado" value
 * @method string      getMunicipio() Returns the current record's "municipio" value
 * @method string      getParr()      Returns the current record's "parr" value
 * @method string      getAsic()      Returns the current record's "asic" value
 * @method string      getCohorte()   Returns the current record's "cohorte" value
 * @method Graduandos8 setId()        Sets the current record's "id" value
 * @method Graduandos8 setN()         Sets the current record's "n" value
 * @method Graduandos8 setTipoDoc()   Sets the current record's "tipo_doc" value
 * @method Graduandos8 setDocIden()   Sets the current record's "doc_iden" value
 * @method Graduandos8 setApe1()      Sets the current record's "ape1" value
 * @method Graduandos8 setApe2()      Sets the current record's "ape2" value
 * @method Graduandos8 setNombres()   Sets the current record's "nombres" value
 * @method Graduandos8 setGene()      Sets the current record's "gene" value
 * @method Graduandos8 setPaisO()     Sets the current record's "pais_o" value
 * @method Graduandos8 setEstado()    Sets the current record's "estado" value
 * @method Graduandos8 setMunicipio() Sets the current record's "municipio" value
 * @method Graduandos8 setParr()      Sets the current record's "parr" value
 * @method Graduandos8 setAsic()      Sets the current record's "asic" value
 * @method Graduandos8 setCohorte()   Sets the current record's "cohorte" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGraduandos8 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('graduandos8');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('n', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo_doc', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('doc_iden', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ape1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ape2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nombres', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('gene', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pais_o', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('municipio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('parr', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('asic', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cohorte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}