<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuarios2', 'doctrine');

/**
 * BaseUsuarios2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $identificacion
 * @property string $usuario
 * @property string $clave
 * 
 * @method integer   getId()             Returns the current record's "id" value
 * @method string    getIdentificacion() Returns the current record's "identificacion" value
 * @method string    getUsuario()        Returns the current record's "usuario" value
 * @method string    getClave()          Returns the current record's "clave" value
 * @method Usuarios2 setId()             Sets the current record's "id" value
 * @method Usuarios2 setIdentificacion() Sets the current record's "identificacion" value
 * @method Usuarios2 setUsuario()        Sets the current record's "usuario" value
 * @method Usuarios2 setClave()          Sets the current record's "clave" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarios2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuarios2');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'usuarios2_id',
             'length' => 4,
             ));
        $this->hasColumn('identificacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('usuario', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('clave', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}