<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Graduados2019Cta', 'doctrine');

/**
 * BaseGraduados2019Cta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nï¿½
 * @property string $tipo de documentos de identidad (v,e,p)
 * @property string $doc_iden
 * @property string $apellido 1
 * @property string $apellido 2
 * @property string $nombres (cantidad de nombres del posible graduando (a)
 * @property string $gï¿½nero
 * @property string $titulo a obtener
 * @property string $paï¿½s de origen
 * @property string $estado
 * @property string $cohorte
 * @property string $nï¿½1
 * @property string $banco
 * @property string $cuenta
 * 
 * @method string           getNï()       Returns the current record's "nï" value
 * @method string           getTipo()     Returns the current record's "tipo" value
 * @method string           getDocIden()  Returns the current record's "doc_iden" value
 * @method string           getApellido() Returns the current record's "apellido" value
 * @method string           getNombres()  Returns the current record's "nombres" value
 * @method string           getGï()       Returns the current record's "gï" value
 * @method string           getTitulo()   Returns the current record's "titulo" value
 * @method string           getPaï()      Returns the current record's "paï" value
 * @method string           getEstado()   Returns the current record's "estado" value
 * @method string           getCohorte()  Returns the current record's "cohorte" value
 * @method string           getBanco()    Returns the current record's "banco" value
 * @method string           getCuenta()   Returns the current record's "cuenta" value
 * @method Graduados2019Cta setNï()       Sets the current record's "nï" value
 * @method Graduados2019Cta setTipo()     Sets the current record's "tipo" value
 * @method Graduados2019Cta setDocIden()  Sets the current record's "doc_iden" value
 * @method Graduados2019Cta setApellido() Sets the current record's "apellido" value
 * @method Graduados2019Cta setNombres()  Sets the current record's "nombres" value
 * @method Graduados2019Cta setGï()       Sets the current record's "gï" value
 * @method Graduados2019Cta setTitulo()   Sets the current record's "titulo" value
 * @method Graduados2019Cta setPaï()      Sets the current record's "paï" value
 * @method Graduados2019Cta setEstado()   Sets the current record's "estado" value
 * @method Graduados2019Cta setCohorte()  Sets the current record's "cohorte" value
 * @method Graduados2019Cta setBanco()    Sets the current record's "banco" value
 * @method Graduados2019Cta setCuenta()   Sets the current record's "cuenta" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGraduados2019Cta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('graduados2019_cta');
        $this->hasColumn('nï¿½', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('tipo de documentos de identidad (v,e,p)', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('doc_iden', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido 1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido 2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nombres (cantidad de nombres del posible graduando (a)', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('gï¿½nero', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('titulo a obtener', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('paï¿½s de origen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cohorte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nï¿½1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('banco', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cuenta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}