<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Notas9Coho', 'doctrine');

/**
 * BaseNotas9Coho
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $id_alumno
 * @property string $id_malla
 * @property string $id_uc
 * @property string $seccion
 * @property string $periodo
 * @property string $nota
 * @property string $id_estado
 * @property string $id_tipo_aldea
 * @property string $certificaciï¿½n
 * @property string $idestado
 * @property string $fecha
 * @property string $asignatura
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method string     getIdAlumno()      Returns the current record's "id_alumno" value
 * @method string     getIdMalla()       Returns the current record's "id_malla" value
 * @method string     getIdUc()          Returns the current record's "id_uc" value
 * @method string     getSeccion()       Returns the current record's "seccion" value
 * @method string     getPeriodo()       Returns the current record's "periodo" value
 * @method string     getNota()          Returns the current record's "nota" value
 * @method string     getIdEstado()      Returns the current record's "id_estado" value
 * @method string     getIdTipoAldea()   Returns the current record's "id_tipo_aldea" value
 * @method string     getCertificaciï()  Returns the current record's "certificaciï" value
 * @method string     getIdestado()      Returns the current record's "idestado" value
 * @method string     getFecha()         Returns the current record's "fecha" value
 * @method string     getAsignatura()    Returns the current record's "asignatura" value
 * @method Notas9Coho setId()            Sets the current record's "id" value
 * @method Notas9Coho setIdAlumno()      Sets the current record's "id_alumno" value
 * @method Notas9Coho setIdMalla()       Sets the current record's "id_malla" value
 * @method Notas9Coho setIdUc()          Sets the current record's "id_uc" value
 * @method Notas9Coho setSeccion()       Sets the current record's "seccion" value
 * @method Notas9Coho setPeriodo()       Sets the current record's "periodo" value
 * @method Notas9Coho setNota()          Sets the current record's "nota" value
 * @method Notas9Coho setIdEstado()      Sets the current record's "id_estado" value
 * @method Notas9Coho setIdTipoAldea()   Sets the current record's "id_tipo_aldea" value
 * @method Notas9Coho setCertificaciï()  Sets the current record's "certificaciï" value
 * @method Notas9Coho setIdestado()      Sets the current record's "idestado" value
 * @method Notas9Coho setFecha()         Sets the current record's "fecha" value
 * @method Notas9Coho setAsignatura()    Sets the current record's "asignatura" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotas9Coho extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notas_9_coho');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_alumno', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_malla', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_uc', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('seccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('periodo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nota', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_estado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_tipo_aldea', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('certificaciï¿½n', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('idestado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('asignatura', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}