<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mmcii', 'doctrine');

/**
 * BaseMmcii
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $idmatricula
 * @property string $ano_en_curso
 * @property string $estamunpar
 * @property string $asic
 * @property string $id_nucleo_docente
 * @property string $nombre
 * @property string $apellido1
 * @property string $apellido2
 * @property string $sexo
 * @property string $fecha_de_nacimiento
 * @property string $tipoidentidad
 * @property string $cedula_de_identidad
 * @property string $numero_de_pasaporte
 * @property string $nacionalidad
 * @property string $pais_de_origen
 * @property string $direccion_particular
 * @property string $localizacion
 * @property string $telefono
 * @property string $correo_electronico
 * @property string $situacion_escolar
 * @property string $procedencia_escolar
 * @property string $centro_escolar_de_procedencia
 * @property string $estado_civil
 * @property string $numero_de_hijos
 * @property string $enfermedades_que_padece_a
 * @property string $enfermedades_que_padece_b
 * @property string $convpadre
 * @property string $convmadre
 * @property string $convconyuge
 * @property string $convhijos
 * @property string $convhermano
 * @property string $convotro
 * @property string $convtotal
 * @property string $ano_todos_ratifmatricula
 * @property string $cohorte
 * @property string $fecha_de_matricula
 * @property string $no_pasa_de_ano
 * @property string $revisado
 * @property string $expedienteincompleto
 * @property string $fotodig
 * @property string $cemsorigen
 * @property string $doble_baja
 * @property string $es_indigena
 * @property string $etnia_indigena
 * @property string $causaalta
 * @property string $programa
 * @property string $estado
 * @property string $estado2
 * @property string $situacion_escolar_b
 * @property string $region
 * @property string $univ
 * @property string $campo0
 * 
 * @method integer getId()                            Returns the current record's "id" value
 * @method string  getIdmatricula()                   Returns the current record's "idmatricula" value
 * @method string  getAnoEnCurso()                    Returns the current record's "ano_en_curso" value
 * @method string  getEstamunpar()                    Returns the current record's "estamunpar" value
 * @method string  getAsic()                          Returns the current record's "asic" value
 * @method string  getIdNucleoDocente()               Returns the current record's "id_nucleo_docente" value
 * @method string  getNombre()                        Returns the current record's "nombre" value
 * @method string  getApellido1()                     Returns the current record's "apellido1" value
 * @method string  getApellido2()                     Returns the current record's "apellido2" value
 * @method string  getSexo()                          Returns the current record's "sexo" value
 * @method string  getFechaDeNacimiento()             Returns the current record's "fecha_de_nacimiento" value
 * @method string  getTipoidentidad()                 Returns the current record's "tipoidentidad" value
 * @method string  getCedulaDeIdentidad()             Returns the current record's "cedula_de_identidad" value
 * @method string  getNumeroDePasaporte()             Returns the current record's "numero_de_pasaporte" value
 * @method string  getNacionalidad()                  Returns the current record's "nacionalidad" value
 * @method string  getPaisDeOrigen()                  Returns the current record's "pais_de_origen" value
 * @method string  getDireccionParticular()           Returns the current record's "direccion_particular" value
 * @method string  getLocalizacion()                  Returns the current record's "localizacion" value
 * @method string  getTelefono()                      Returns the current record's "telefono" value
 * @method string  getCorreoElectronico()             Returns the current record's "correo_electronico" value
 * @method string  getSituacionEscolar()              Returns the current record's "situacion_escolar" value
 * @method string  getProcedenciaEscolar()            Returns the current record's "procedencia_escolar" value
 * @method string  getCentroEscolarDeProcedencia()    Returns the current record's "centro_escolar_de_procedencia" value
 * @method string  getEstadoCivil()                   Returns the current record's "estado_civil" value
 * @method string  getNumeroDeHijos()                 Returns the current record's "numero_de_hijos" value
 * @method string  getEnfermedadesQuePadeceA()        Returns the current record's "enfermedades_que_padece_a" value
 * @method string  getEnfermedadesQuePadeceB()        Returns the current record's "enfermedades_que_padece_b" value
 * @method string  getConvpadre()                     Returns the current record's "convpadre" value
 * @method string  getConvmadre()                     Returns the current record's "convmadre" value
 * @method string  getConvconyuge()                   Returns the current record's "convconyuge" value
 * @method string  getConvhijos()                     Returns the current record's "convhijos" value
 * @method string  getConvhermano()                   Returns the current record's "convhermano" value
 * @method string  getConvotro()                      Returns the current record's "convotro" value
 * @method string  getConvtotal()                     Returns the current record's "convtotal" value
 * @method string  getAnoTodosRatifmatricula()        Returns the current record's "ano_todos_ratifmatricula" value
 * @method string  getCohorte()                       Returns the current record's "cohorte" value
 * @method string  getFechaDeMatricula()              Returns the current record's "fecha_de_matricula" value
 * @method string  getNoPasaDeAno()                   Returns the current record's "no_pasa_de_ano" value
 * @method string  getRevisado()                      Returns the current record's "revisado" value
 * @method string  getExpedienteincompleto()          Returns the current record's "expedienteincompleto" value
 * @method string  getFotodig()                       Returns the current record's "fotodig" value
 * @method string  getCemsorigen()                    Returns the current record's "cemsorigen" value
 * @method string  getDobleBaja()                     Returns the current record's "doble_baja" value
 * @method string  getEsIndigena()                    Returns the current record's "es_indigena" value
 * @method string  getEtniaIndigena()                 Returns the current record's "etnia_indigena" value
 * @method string  getCausaalta()                     Returns the current record's "causaalta" value
 * @method string  getPrograma()                      Returns the current record's "programa" value
 * @method string  getEstado()                        Returns the current record's "estado" value
 * @method string  getEstado2()                       Returns the current record's "estado2" value
 * @method string  getSituacionEscolarB()             Returns the current record's "situacion_escolar_b" value
 * @method string  getRegion()                        Returns the current record's "region" value
 * @method string  getUniv()                          Returns the current record's "univ" value
 * @method string  getCampo0()                        Returns the current record's "campo0" value
 * @method Mmcii   setId()                            Sets the current record's "id" value
 * @method Mmcii   setIdmatricula()                   Sets the current record's "idmatricula" value
 * @method Mmcii   setAnoEnCurso()                    Sets the current record's "ano_en_curso" value
 * @method Mmcii   setEstamunpar()                    Sets the current record's "estamunpar" value
 * @method Mmcii   setAsic()                          Sets the current record's "asic" value
 * @method Mmcii   setIdNucleoDocente()               Sets the current record's "id_nucleo_docente" value
 * @method Mmcii   setNombre()                        Sets the current record's "nombre" value
 * @method Mmcii   setApellido1()                     Sets the current record's "apellido1" value
 * @method Mmcii   setApellido2()                     Sets the current record's "apellido2" value
 * @method Mmcii   setSexo()                          Sets the current record's "sexo" value
 * @method Mmcii   setFechaDeNacimiento()             Sets the current record's "fecha_de_nacimiento" value
 * @method Mmcii   setTipoidentidad()                 Sets the current record's "tipoidentidad" value
 * @method Mmcii   setCedulaDeIdentidad()             Sets the current record's "cedula_de_identidad" value
 * @method Mmcii   setNumeroDePasaporte()             Sets the current record's "numero_de_pasaporte" value
 * @method Mmcii   setNacionalidad()                  Sets the current record's "nacionalidad" value
 * @method Mmcii   setPaisDeOrigen()                  Sets the current record's "pais_de_origen" value
 * @method Mmcii   setDireccionParticular()           Sets the current record's "direccion_particular" value
 * @method Mmcii   setLocalizacion()                  Sets the current record's "localizacion" value
 * @method Mmcii   setTelefono()                      Sets the current record's "telefono" value
 * @method Mmcii   setCorreoElectronico()             Sets the current record's "correo_electronico" value
 * @method Mmcii   setSituacionEscolar()              Sets the current record's "situacion_escolar" value
 * @method Mmcii   setProcedenciaEscolar()            Sets the current record's "procedencia_escolar" value
 * @method Mmcii   setCentroEscolarDeProcedencia()    Sets the current record's "centro_escolar_de_procedencia" value
 * @method Mmcii   setEstadoCivil()                   Sets the current record's "estado_civil" value
 * @method Mmcii   setNumeroDeHijos()                 Sets the current record's "numero_de_hijos" value
 * @method Mmcii   setEnfermedadesQuePadeceA()        Sets the current record's "enfermedades_que_padece_a" value
 * @method Mmcii   setEnfermedadesQuePadeceB()        Sets the current record's "enfermedades_que_padece_b" value
 * @method Mmcii   setConvpadre()                     Sets the current record's "convpadre" value
 * @method Mmcii   setConvmadre()                     Sets the current record's "convmadre" value
 * @method Mmcii   setConvconyuge()                   Sets the current record's "convconyuge" value
 * @method Mmcii   setConvhijos()                     Sets the current record's "convhijos" value
 * @method Mmcii   setConvhermano()                   Sets the current record's "convhermano" value
 * @method Mmcii   setConvotro()                      Sets the current record's "convotro" value
 * @method Mmcii   setConvtotal()                     Sets the current record's "convtotal" value
 * @method Mmcii   setAnoTodosRatifmatricula()        Sets the current record's "ano_todos_ratifmatricula" value
 * @method Mmcii   setCohorte()                       Sets the current record's "cohorte" value
 * @method Mmcii   setFechaDeMatricula()              Sets the current record's "fecha_de_matricula" value
 * @method Mmcii   setNoPasaDeAno()                   Sets the current record's "no_pasa_de_ano" value
 * @method Mmcii   setRevisado()                      Sets the current record's "revisado" value
 * @method Mmcii   setExpedienteincompleto()          Sets the current record's "expedienteincompleto" value
 * @method Mmcii   setFotodig()                       Sets the current record's "fotodig" value
 * @method Mmcii   setCemsorigen()                    Sets the current record's "cemsorigen" value
 * @method Mmcii   setDobleBaja()                     Sets the current record's "doble_baja" value
 * @method Mmcii   setEsIndigena()                    Sets the current record's "es_indigena" value
 * @method Mmcii   setEtniaIndigena()                 Sets the current record's "etnia_indigena" value
 * @method Mmcii   setCausaalta()                     Sets the current record's "causaalta" value
 * @method Mmcii   setPrograma()                      Sets the current record's "programa" value
 * @method Mmcii   setEstado()                        Sets the current record's "estado" value
 * @method Mmcii   setEstado2()                       Sets the current record's "estado2" value
 * @method Mmcii   setSituacionEscolarB()             Sets the current record's "situacion_escolar_b" value
 * @method Mmcii   setRegion()                        Sets the current record's "region" value
 * @method Mmcii   setUniv()                          Sets the current record's "univ" value
 * @method Mmcii   setCampo0()                        Sets the current record's "campo0" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMmcii extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mmcii');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('idmatricula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ano_en_curso', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estamunpar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('asic', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_nucleo_docente', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sexo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_de_nacimiento', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipoidentidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cedula_de_identidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('numero_de_pasaporte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nacionalidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pais_de_origen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('direccion_particular', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('localizacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('correo_electronico', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('situacion_escolar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('procedencia_escolar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('centro_escolar_de_procedencia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado_civil', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('numero_de_hijos', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('enfermedades_que_padece_a', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('enfermedades_que_padece_b', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convpadre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convmadre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convconyuge', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convhijos', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convhermano', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convotro', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convtotal', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ano_todos_ratifmatricula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cohorte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_de_matricula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('no_pasa_de_ano', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('revisado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('expedienteincompleto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fotodig', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cemsorigen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('doble_baja', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('es_indigena', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('etnia_indigena', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('causaalta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('programa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('situacion_escolar_b', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('region', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('univ', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo0', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}