<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PnfPre', 'doctrine');

/**
 * BasePnfPre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $estado_id
 * @property string $descripcion
 * @property integer $pnf_id
 * @property Estado $Estado
 * @property Doctrine_Collection $PreinscripcionCurso
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method integer             getEstadoId()            Returns the current record's "estado_id" value
 * @method string              getDescripcion()         Returns the current record's "descripcion" value
 * @method integer             getPnfId()               Returns the current record's "pnf_id" value
 * @method Estado              getEstado()              Returns the current record's "Estado" value
 * @method Doctrine_Collection getPreinscripcionCurso() Returns the current record's "PreinscripcionCurso" collection
 * @method PnfPre              setId()                  Sets the current record's "id" value
 * @method PnfPre              setEstadoId()            Sets the current record's "estado_id" value
 * @method PnfPre              setDescripcion()         Sets the current record's "descripcion" value
 * @method PnfPre              setPnfId()               Sets the current record's "pnf_id" value
 * @method PnfPre              setEstado()              Sets the current record's "Estado" value
 * @method PnfPre              setPreinscripcionCurso() Sets the current record's "PreinscripcionCurso" collection
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePnfPre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pnf_pre');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'pnf_pre_id',
             'length' => 4,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pnf_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'estado_id',
             'foreign' => 'id'));

        $this->hasMany('PreinscripcionCurso', array(
             'local' => 'id',
             'foreign' => 'pnf_pre_id'));
    }
}