<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Indice', 'doctrine');

/**
 * BaseIndice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pnf_id
 * @property integer $estudiante_id
 * @property integer $estado_id
 * @property decimal $trunc
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method integer getPnfId()         Returns the current record's "pnf_id" value
 * @method integer getEstudianteId()  Returns the current record's "estudiante_id" value
 * @method integer getEstadoId()      Returns the current record's "estado_id" value
 * @method decimal getTrunc()         Returns the current record's "trunc" value
 * @method Indice  setId()            Sets the current record's "id" value
 * @method Indice  setPnfId()         Sets the current record's "pnf_id" value
 * @method Indice  setEstudianteId()  Sets the current record's "estudiante_id" value
 * @method Indice  setEstadoId()      Sets the current record's "estado_id" value
 * @method Indice  setTrunc()         Sets the current record's "trunc" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIndice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('indice');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('pnf_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('estudiante_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('trunc', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}