<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Graduados9', 'doctrine');

/**
 * BaseGraduados9
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $idmatricula
 * @property string $aï¿½o en curso
 * @property string $estamunpar
 * @property string $asic
 * @property string $id nï¿½cleo docente
 * @property string $nombre
 * @property string $apellido1
 * @property string $apellido2
 * @property string $sexo
 * @property string $fecha de nacimiento
 * @property string $tipoidentidad
 * @property string $cï¿½dula de identidad
 * @property string $nï¿½mero de pasaporte
 * @property string $nacionalidad
 * @property string $paï¿½s de origen
 * @property string $direcciï¿½n particular
 * @property string $localizaciï¿½n
 * @property string $telï¿½fono
 * @property string $correo electrï¿½nico
 * @property string $situaciï¿½n escolar
 * @property string $procedencia escolar
 * @property string $centro escolar de procedencia
 * @property string $estado civil
 * @property string $nï¿½mero de hijos
 * @property string $enfermedades que padece 1
 * @property string $enfermedades que padece 2
 * @property string $convpadre
 * @property string $convmadre
 * @property string $convcï¿½nyuge
 * @property string $convhijos
 * @property string $convhermano
 * @property string $convotro
 * @property string $convtotal
 * @property string $aï¿½o-todos.ratifmatrï¿½cula
 * @property string $cohorte
 * @property string $fecha de matrï¿½cula
 * @property string $no pasa de aï¿½o
 * @property string $revisado
 * @property string $expedienteincompleto
 * @property string $fotodig
 * @property string $cemsorigen
 * @property string $doble baja
 * @property string $es indï¿½gena
 * @property string $etnia indï¿½gena
 * @property string $causaalta
 * @property string $programa
 * @property string $estado
 * @property string $estado2
 * @property string $situacion escolar
 * @property string $regiï¿½n
 * @property string $univ
 * @property string $campo0
 * 
 * @method string     getId()                   Returns the current record's "id" value
 * @method string     getIdmatricula()          Returns the current record's "idmatricula" value
 * @method string     getAï()                   Returns the current record's "aï" value
 * @method string     getEstamunpar()           Returns the current record's "estamunpar" value
 * @method string     getAsic()                 Returns the current record's "asic" value
 * @method string     getNombre()               Returns the current record's "nombre" value
 * @method string     getApellido1()            Returns the current record's "apellido1" value
 * @method string     getApellido2()            Returns the current record's "apellido2" value
 * @method string     getSexo()                 Returns the current record's "sexo" value
 * @method string     getFecha()                Returns the current record's "fecha" value
 * @method string     getTipoidentidad()        Returns the current record's "tipoidentidad" value
 * @method string     getCï()                   Returns the current record's "cï" value
 * @method string     getNï()                   Returns the current record's "nï" value
 * @method string     getNacionalidad()         Returns the current record's "nacionalidad" value
 * @method string     getPaï()                  Returns the current record's "paï" value
 * @method string     getDirecciï()             Returns the current record's "direcciï" value
 * @method string     getLocalizaciï()          Returns the current record's "localizaciï" value
 * @method string     getTelï()                 Returns the current record's "telï" value
 * @method string     getCorreo()               Returns the current record's "correo" value
 * @method string     getSituaciï()             Returns the current record's "situaciï" value
 * @method string     getProcedencia()          Returns the current record's "procedencia" value
 * @method string     getCentro()               Returns the current record's "centro" value
 * @method string     getEstado()               Returns the current record's "estado" value
 * @method string     getEnfermedades()         Returns the current record's "enfermedades" value
 * @method string     getConvpadre()            Returns the current record's "convpadre" value
 * @method string     getConvmadre()            Returns the current record's "convmadre" value
 * @method string     getConvcï()               Returns the current record's "convcï" value
 * @method string     getConvhijos()            Returns the current record's "convhijos" value
 * @method string     getConvhermano()          Returns the current record's "convhermano" value
 * @method string     getConvotro()             Returns the current record's "convotro" value
 * @method string     getConvtotal()            Returns the current record's "convtotal" value
 * @method string     getCohorte()              Returns the current record's "cohorte" value
 * @method string     getNo()                   Returns the current record's "no" value
 * @method string     getRevisado()             Returns the current record's "revisado" value
 * @method string     getExpedienteincompleto() Returns the current record's "expedienteincompleto" value
 * @method string     getFotodig()              Returns the current record's "fotodig" value
 * @method string     getCemsorigen()           Returns the current record's "cemsorigen" value
 * @method string     getDoble()                Returns the current record's "doble" value
 * @method string     getEs()                   Returns the current record's "es" value
 * @method string     getEtnia()                Returns the current record's "etnia" value
 * @method string     getCausaalta()            Returns the current record's "causaalta" value
 * @method string     getPrograma()             Returns the current record's "programa" value
 * @method string     getEstado2()              Returns the current record's "estado2" value
 * @method string     getSituacion()            Returns the current record's "situacion" value
 * @method string     getRegiï()                Returns the current record's "regiï" value
 * @method string     getUniv()                 Returns the current record's "univ" value
 * @method string     getCampo0()               Returns the current record's "campo0" value
 * @method Graduados9 setId()                   Sets the current record's "id" value
 * @method Graduados9 setIdmatricula()          Sets the current record's "idmatricula" value
 * @method Graduados9 setAï()                   Sets the current record's "aï" value
 * @method Graduados9 setEstamunpar()           Sets the current record's "estamunpar" value
 * @method Graduados9 setAsic()                 Sets the current record's "asic" value
 * @method Graduados9 setNombre()               Sets the current record's "nombre" value
 * @method Graduados9 setApellido1()            Sets the current record's "apellido1" value
 * @method Graduados9 setApellido2()            Sets the current record's "apellido2" value
 * @method Graduados9 setSexo()                 Sets the current record's "sexo" value
 * @method Graduados9 setFecha()                Sets the current record's "fecha" value
 * @method Graduados9 setTipoidentidad()        Sets the current record's "tipoidentidad" value
 * @method Graduados9 setCï()                   Sets the current record's "cï" value
 * @method Graduados9 setNï()                   Sets the current record's "nï" value
 * @method Graduados9 setNacionalidad()         Sets the current record's "nacionalidad" value
 * @method Graduados9 setPaï()                  Sets the current record's "paï" value
 * @method Graduados9 setDirecciï()             Sets the current record's "direcciï" value
 * @method Graduados9 setLocalizaciï()          Sets the current record's "localizaciï" value
 * @method Graduados9 setTelï()                 Sets the current record's "telï" value
 * @method Graduados9 setCorreo()               Sets the current record's "correo" value
 * @method Graduados9 setSituaciï()             Sets the current record's "situaciï" value
 * @method Graduados9 setProcedencia()          Sets the current record's "procedencia" value
 * @method Graduados9 setCentro()               Sets the current record's "centro" value
 * @method Graduados9 setEstado()               Sets the current record's "estado" value
 * @method Graduados9 setEnfermedades()         Sets the current record's "enfermedades" value
 * @method Graduados9 setConvpadre()            Sets the current record's "convpadre" value
 * @method Graduados9 setConvmadre()            Sets the current record's "convmadre" value
 * @method Graduados9 setConvcï()               Sets the current record's "convcï" value
 * @method Graduados9 setConvhijos()            Sets the current record's "convhijos" value
 * @method Graduados9 setConvhermano()          Sets the current record's "convhermano" value
 * @method Graduados9 setConvotro()             Sets the current record's "convotro" value
 * @method Graduados9 setConvtotal()            Sets the current record's "convtotal" value
 * @method Graduados9 setCohorte()              Sets the current record's "cohorte" value
 * @method Graduados9 setNo()                   Sets the current record's "no" value
 * @method Graduados9 setRevisado()             Sets the current record's "revisado" value
 * @method Graduados9 setExpedienteincompleto() Sets the current record's "expedienteincompleto" value
 * @method Graduados9 setFotodig()              Sets the current record's "fotodig" value
 * @method Graduados9 setCemsorigen()           Sets the current record's "cemsorigen" value
 * @method Graduados9 setDoble()                Sets the current record's "doble" value
 * @method Graduados9 setEs()                   Sets the current record's "es" value
 * @method Graduados9 setEtnia()                Sets the current record's "etnia" value
 * @method Graduados9 setCausaalta()            Sets the current record's "causaalta" value
 * @method Graduados9 setPrograma()             Sets the current record's "programa" value
 * @method Graduados9 setEstado2()              Sets the current record's "estado2" value
 * @method Graduados9 setSituacion()            Sets the current record's "situacion" value
 * @method Graduados9 setRegiï()                Sets the current record's "regiï" value
 * @method Graduados9 setUniv()                 Sets the current record's "univ" value
 * @method Graduados9 setCampo0()               Sets the current record's "campo0" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGraduados9 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('graduados9');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('idmatricula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('aï¿½o en curso', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estamunpar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('asic', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id nï¿½cleo docente', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sexo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha de nacimiento', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipoidentidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cï¿½dula de identidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nï¿½mero de pasaporte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nacionalidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('paï¿½s de origen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('direcciï¿½n particular', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('localizaciï¿½n', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telï¿½fono', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('correo electrï¿½nico', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('situaciï¿½n escolar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('procedencia escolar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('centro escolar de procedencia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado civil', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nï¿½mero de hijos', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('enfermedades que padece 1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('enfermedades que padece 2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convpadre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convmadre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convcï¿½nyuge', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convhijos', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convhermano', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convotro', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('convtotal', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('aï¿½o-todos.ratifmatrï¿½cula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cohorte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha de matrï¿½cula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('no pasa de aï¿½o', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('revisado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('expedienteincompleto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fotodig', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cemsorigen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('doble baja', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('es indï¿½gena', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('etnia indï¿½gena', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('causaalta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('programa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('situacion escolar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('regiï¿½n', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('univ', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('campo0', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}