<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estado', 'doctrine');

/**
 * BaseEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property Doctrine_Collection $Traslado
 * @property Doctrine_Collection $Traslado_4
 * @property Doctrine_Collection $Preinscripcion
 * @property Doctrine_Collection $PnfPre
 * @property Doctrine_Collection $Estudiante
 * @property Doctrine_Collection $Estudiante_10
 * @property Doctrine_Collection $PreinscripcionCurso
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getDescripcion()         Returns the current record's "descripcion" value
 * @method Doctrine_Collection getTraslado()            Returns the current record's "Traslado" collection
 * @method Doctrine_Collection getTraslado4()           Returns the current record's "Traslado_4" collection
 * @method Doctrine_Collection getPreinscripcion()      Returns the current record's "Preinscripcion" collection
 * @method Doctrine_Collection getPnfPre()              Returns the current record's "PnfPre" collection
 * @method Doctrine_Collection getEstudiante()          Returns the current record's "Estudiante" collection
 * @method Doctrine_Collection getEstudiante10()        Returns the current record's "Estudiante_10" collection
 * @method Doctrine_Collection getPreinscripcionCurso() Returns the current record's "PreinscripcionCurso" collection
 * @method Estado              setId()                  Sets the current record's "id" value
 * @method Estado              setDescripcion()         Sets the current record's "descripcion" value
 * @method Estado              setTraslado()            Sets the current record's "Traslado" collection
 * @method Estado              setTraslado4()           Sets the current record's "Traslado_4" collection
 * @method Estado              setPreinscripcion()      Sets the current record's "Preinscripcion" collection
 * @method Estado              setPnfPre()              Sets the current record's "PnfPre" collection
 * @method Estado              setEstudiante()          Sets the current record's "Estudiante" collection
 * @method Estado              setEstudiante10()        Sets the current record's "Estudiante_10" collection
 * @method Estado              setPreinscripcionCurso() Sets the current record's "PreinscripcionCurso" collection
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'estado_id',
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Traslado', array(
             'local' => 'id',
             'foreign' => 'estado_emisor_id'));

        $this->hasMany('Traslado as Traslado_4', array(
             'local' => 'id',
             'foreign' => 'estado_receptor_id'));

        $this->hasMany('Preinscripcion', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('PnfPre', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('Estudiante', array(
             'local' => 'id',
             'foreign' => 'asic_estado_id'));

        $this->hasMany('Estudiante as Estudiante_10', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('PreinscripcionCurso', array(
             'local' => 'id',
             'foreign' => 'estado_id'));
    }
}