<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudianteMmcEstado', 'doctrine');

/**
 * BaseEstudianteMmcEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $aï¿½o en curso
 * @property string $estado
 * @property string $municipio
 * @property string $parroquia
 * @property string $asic
 * @property string $id nï¿½cleo docente
 * @property string $nombre
 * @property string $apellido1
 * @property string $apellido2
 * @property string $sexo
 * @property string $fecha de nacimiento
 * @property string $tipoidentidad
 * @property string $cedula
 * @property string $nï¿½mero de pasaporte
 * @property string $nacionalidad
 * @property string $paï¿½s de origen
 * @property string $direcciï¿½n particular
 * @property string $localizaciï¿½n
 * @property string $telï¿½fono
 * @property string $correo electrï¿½nico
 * @property string $situaciï¿½n escolar
 * @property string $procedencia escolar
 * @property string $aï¿½o-todos.ratifmatrï¿½cula
 * @property string $cohorte
 * @property string $fecha de matrï¿½cula
 * @property string $no pasa de aï¿½o
 * @property string $revisado
 * @property string $expedienteincompleto
 * @property string $fotodig
 * @property string $cemsorigen
 * @property string $doble baja
 * @property string $es indï¿½gena
 * @property string $etnia indï¿½gena
 * @property string $causaalta
 * @property string $programa
 * @property string $estado2
 * @property string $situacion escolar
 * @property string $regiï¿½n
 * @property string $univ
 * @property integer $estado_id
 * 
 * @method string              getId()                   Returns the current record's "id" value
 * @method string              getAï()                   Returns the current record's "aï" value
 * @method string              getEstado()               Returns the current record's "estado" value
 * @method string              getMunicipio()            Returns the current record's "municipio" value
 * @method string              getParroquia()            Returns the current record's "parroquia" value
 * @method string              getAsic()                 Returns the current record's "asic" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method string              getApellido1()            Returns the current record's "apellido1" value
 * @method string              getApellido2()            Returns the current record's "apellido2" value
 * @method string              getSexo()                 Returns the current record's "sexo" value
 * @method string              getFecha()                Returns the current record's "fecha" value
 * @method string              getTipoidentidad()        Returns the current record's "tipoidentidad" value
 * @method string              getCedula()               Returns the current record's "cedula" value
 * @method string              getNï()                   Returns the current record's "nï" value
 * @method string              getNacionalidad()         Returns the current record's "nacionalidad" value
 * @method string              getPaï()                  Returns the current record's "paï" value
 * @method string              getDirecciï()             Returns the current record's "direcciï" value
 * @method string              getLocalizaciï()          Returns the current record's "localizaciï" value
 * @method string              getTelï()                 Returns the current record's "telï" value
 * @method string              getCorreo()               Returns the current record's "correo" value
 * @method string              getSituaciï()             Returns the current record's "situaciï" value
 * @method string              getProcedencia()          Returns the current record's "procedencia" value
 * @method string              getCohorte()              Returns the current record's "cohorte" value
 * @method string              getNo()                   Returns the current record's "no" value
 * @method string              getRevisado()             Returns the current record's "revisado" value
 * @method string              getExpedienteincompleto() Returns the current record's "expedienteincompleto" value
 * @method string              getFotodig()              Returns the current record's "fotodig" value
 * @method string              getCemsorigen()           Returns the current record's "cemsorigen" value
 * @method string              getDoble()                Returns the current record's "doble" value
 * @method string              getEs()                   Returns the current record's "es" value
 * @method string              getEtnia()                Returns the current record's "etnia" value
 * @method string              getCausaalta()            Returns the current record's "causaalta" value
 * @method string              getPrograma()             Returns the current record's "programa" value
 * @method string              getEstado2()              Returns the current record's "estado2" value
 * @method string              getSituacion()            Returns the current record's "situacion" value
 * @method string              getRegiï()                Returns the current record's "regiï" value
 * @method string              getUniv()                 Returns the current record's "univ" value
 * @method integer             getEstadoId()             Returns the current record's "estado_id" value
 * @method EstudianteMmcEstado setId()                   Sets the current record's "id" value
 * @method EstudianteMmcEstado setAï()                   Sets the current record's "aï" value
 * @method EstudianteMmcEstado setEstado()               Sets the current record's "estado" value
 * @method EstudianteMmcEstado setMunicipio()            Sets the current record's "municipio" value
 * @method EstudianteMmcEstado setParroquia()            Sets the current record's "parroquia" value
 * @method EstudianteMmcEstado setAsic()                 Sets the current record's "asic" value
 * @method EstudianteMmcEstado setNombre()               Sets the current record's "nombre" value
 * @method EstudianteMmcEstado setApellido1()            Sets the current record's "apellido1" value
 * @method EstudianteMmcEstado setApellido2()            Sets the current record's "apellido2" value
 * @method EstudianteMmcEstado setSexo()                 Sets the current record's "sexo" value
 * @method EstudianteMmcEstado setFecha()                Sets the current record's "fecha" value
 * @method EstudianteMmcEstado setTipoidentidad()        Sets the current record's "tipoidentidad" value
 * @method EstudianteMmcEstado setCedula()               Sets the current record's "cedula" value
 * @method EstudianteMmcEstado setNï()                   Sets the current record's "nï" value
 * @method EstudianteMmcEstado setNacionalidad()         Sets the current record's "nacionalidad" value
 * @method EstudianteMmcEstado setPaï()                  Sets the current record's "paï" value
 * @method EstudianteMmcEstado setDirecciï()             Sets the current record's "direcciï" value
 * @method EstudianteMmcEstado setLocalizaciï()          Sets the current record's "localizaciï" value
 * @method EstudianteMmcEstado setTelï()                 Sets the current record's "telï" value
 * @method EstudianteMmcEstado setCorreo()               Sets the current record's "correo" value
 * @method EstudianteMmcEstado setSituaciï()             Sets the current record's "situaciï" value
 * @method EstudianteMmcEstado setProcedencia()          Sets the current record's "procedencia" value
 * @method EstudianteMmcEstado setCohorte()              Sets the current record's "cohorte" value
 * @method EstudianteMmcEstado setNo()                   Sets the current record's "no" value
 * @method EstudianteMmcEstado setRevisado()             Sets the current record's "revisado" value
 * @method EstudianteMmcEstado setExpedienteincompleto() Sets the current record's "expedienteincompleto" value
 * @method EstudianteMmcEstado setFotodig()              Sets the current record's "fotodig" value
 * @method EstudianteMmcEstado setCemsorigen()           Sets the current record's "cemsorigen" value
 * @method EstudianteMmcEstado setDoble()                Sets the current record's "doble" value
 * @method EstudianteMmcEstado setEs()                   Sets the current record's "es" value
 * @method EstudianteMmcEstado setEtnia()                Sets the current record's "etnia" value
 * @method EstudianteMmcEstado setCausaalta()            Sets the current record's "causaalta" value
 * @method EstudianteMmcEstado setPrograma()             Sets the current record's "programa" value
 * @method EstudianteMmcEstado setEstado2()              Sets the current record's "estado2" value
 * @method EstudianteMmcEstado setSituacion()            Sets the current record's "situacion" value
 * @method EstudianteMmcEstado setRegiï()                Sets the current record's "regiï" value
 * @method EstudianteMmcEstado setUniv()                 Sets the current record's "univ" value
 * @method EstudianteMmcEstado setEstadoId()             Sets the current record's "estado_id" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudianteMmcEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante_mmc_estado');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('aï¿½o en curso', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('municipio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('parroquia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('asic', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id nï¿½cleo docente', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sexo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha de nacimiento', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipoidentidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cedula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nï¿½mero de pasaporte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nacionalidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('paï¿½s de origen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('direcciï¿½n particular', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('localizaciï¿½n', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telï¿½fono', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('correo electrï¿½nico', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('situaciï¿½n escolar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('procedencia escolar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('aï¿½o-todos.ratifmatrï¿½cula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cohorte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha de matrï¿½cula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('no pasa de aï¿½o', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('revisado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('expedienteincompleto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fotodig', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cemsorigen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('doble baja', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('es indï¿½gena', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('etnia indï¿½gena', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('causaalta', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('programa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('situacion escolar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('regiï¿½n', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('univ', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}