<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Minimos', 'doctrine');

/**
 * BaseMinimos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $cedula
 * @property string $nombre
 * @property string $apellido1
 * @property string $apellido2
 * @property string $sexo
 * @property string $estado
 * @property string $municipio
 * @property string $parroquia
 * @property string $asic
 * @property string $n_docente
 * @property string $f_nac
 * @property string $tipo_identidad
 * @property string $pasaporte
 * @property string $nacionalidad
 * @property string $pais_origen
 * @property string $direccion
 * @property string $localiz
 * @property string $telefono
 * @property string $correo
 * @property string $sit_esc
 * @property string $curso
 * @property string $cohorte
 * @property string $matricula
 * @property string $programa
 * 
 * @method integer getId()             Returns the current record's "id" value
 * @method string  getCedula()         Returns the current record's "cedula" value
 * @method string  getNombre()         Returns the current record's "nombre" value
 * @method string  getApellido1()      Returns the current record's "apellido1" value
 * @method string  getApellido2()      Returns the current record's "apellido2" value
 * @method string  getSexo()           Returns the current record's "sexo" value
 * @method string  getEstado()         Returns the current record's "estado" value
 * @method string  getMunicipio()      Returns the current record's "municipio" value
 * @method string  getParroquia()      Returns the current record's "parroquia" value
 * @method string  getAsic()           Returns the current record's "asic" value
 * @method string  getNDocente()       Returns the current record's "n_docente" value
 * @method string  getFNac()           Returns the current record's "f_nac" value
 * @method string  getTipoIdentidad()  Returns the current record's "tipo_identidad" value
 * @method string  getPasaporte()      Returns the current record's "pasaporte" value
 * @method string  getNacionalidad()   Returns the current record's "nacionalidad" value
 * @method string  getPaisOrigen()     Returns the current record's "pais_origen" value
 * @method string  getDireccion()      Returns the current record's "direccion" value
 * @method string  getLocaliz()        Returns the current record's "localiz" value
 * @method string  getTelefono()       Returns the current record's "telefono" value
 * @method string  getCorreo()         Returns the current record's "correo" value
 * @method string  getSitEsc()         Returns the current record's "sit_esc" value
 * @method string  getCurso()          Returns the current record's "curso" value
 * @method string  getCohorte()        Returns the current record's "cohorte" value
 * @method string  getMatricula()      Returns the current record's "matricula" value
 * @method string  getPrograma()       Returns the current record's "programa" value
 * @method Minimos setId()             Sets the current record's "id" value
 * @method Minimos setCedula()         Sets the current record's "cedula" value
 * @method Minimos setNombre()         Sets the current record's "nombre" value
 * @method Minimos setApellido1()      Sets the current record's "apellido1" value
 * @method Minimos setApellido2()      Sets the current record's "apellido2" value
 * @method Minimos setSexo()           Sets the current record's "sexo" value
 * @method Minimos setEstado()         Sets the current record's "estado" value
 * @method Minimos setMunicipio()      Sets the current record's "municipio" value
 * @method Minimos setParroquia()      Sets the current record's "parroquia" value
 * @method Minimos setAsic()           Sets the current record's "asic" value
 * @method Minimos setNDocente()       Sets the current record's "n_docente" value
 * @method Minimos setFNac()           Sets the current record's "f_nac" value
 * @method Minimos setTipoIdentidad()  Sets the current record's "tipo_identidad" value
 * @method Minimos setPasaporte()      Sets the current record's "pasaporte" value
 * @method Minimos setNacionalidad()   Sets the current record's "nacionalidad" value
 * @method Minimos setPaisOrigen()     Sets the current record's "pais_origen" value
 * @method Minimos setDireccion()      Sets the current record's "direccion" value
 * @method Minimos setLocaliz()        Sets the current record's "localiz" value
 * @method Minimos setTelefono()       Sets the current record's "telefono" value
 * @method Minimos setCorreo()         Sets the current record's "correo" value
 * @method Minimos setSitEsc()         Sets the current record's "sit_esc" value
 * @method Minimos setCurso()          Sets the current record's "curso" value
 * @method Minimos setCohorte()        Sets the current record's "cohorte" value
 * @method Minimos setMatricula()      Sets the current record's "matricula" value
 * @method Minimos setPrograma()       Sets the current record's "programa" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMinimos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('minimos');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('cedula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('apellido2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sexo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('municipio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('parroquia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('asic', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('n_docente', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('f_nac', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo_identidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pasaporte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nacionalidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pais_origen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('localiz', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('correo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sit_esc', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('curso', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cohorte', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('matricula', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('programa', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}