<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Opsu2', 'doctrine');

/**
 * BaseOpsu2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_universidad
 * @property string $nucleo
 * @property string $carrera
 * @property string $id_rusnies
 * @property string $nacionalidad
 * @property string $identificacion
 * @property string $nombres
 * @property string $rama
 * @property string $anio_graduacion
 * @property string $ia
 * @property string $semestre
 * @property string $telefono
 * @property string $correo
 * @property integer $estado_id
 * @property string $pnf_id
 * @property boolean $transferir
 * 
 * @method integer getId()                 Returns the current record's "id" value
 * @method string  getNombreUniversidad()  Returns the current record's "nombre_universidad" value
 * @method string  getNucleo()             Returns the current record's "nucleo" value
 * @method string  getCarrera()            Returns the current record's "carrera" value
 * @method string  getIdRusnies()          Returns the current record's "id_rusnies" value
 * @method string  getNacionalidad()       Returns the current record's "nacionalidad" value
 * @method string  getIdentificacion()     Returns the current record's "identificacion" value
 * @method string  getNombres()            Returns the current record's "nombres" value
 * @method string  getRama()               Returns the current record's "rama" value
 * @method string  getAnioGraduacion()     Returns the current record's "anio_graduacion" value
 * @method string  getIa()                 Returns the current record's "ia" value
 * @method string  getSemestre()           Returns the current record's "semestre" value
 * @method string  getTelefono()           Returns the current record's "telefono" value
 * @method string  getCorreo()             Returns the current record's "correo" value
 * @method integer getEstadoId()           Returns the current record's "estado_id" value
 * @method string  getPnfId()              Returns the current record's "pnf_id" value
 * @method boolean getTransferir()         Returns the current record's "transferir" value
 * @method Opsu2   setId()                 Sets the current record's "id" value
 * @method Opsu2   setNombreUniversidad()  Sets the current record's "nombre_universidad" value
 * @method Opsu2   setNucleo()             Sets the current record's "nucleo" value
 * @method Opsu2   setCarrera()            Sets the current record's "carrera" value
 * @method Opsu2   setIdRusnies()          Sets the current record's "id_rusnies" value
 * @method Opsu2   setNacionalidad()       Sets the current record's "nacionalidad" value
 * @method Opsu2   setIdentificacion()     Sets the current record's "identificacion" value
 * @method Opsu2   setNombres()            Sets the current record's "nombres" value
 * @method Opsu2   setRama()               Sets the current record's "rama" value
 * @method Opsu2   setAnioGraduacion()     Sets the current record's "anio_graduacion" value
 * @method Opsu2   setIa()                 Sets the current record's "ia" value
 * @method Opsu2   setSemestre()           Sets the current record's "semestre" value
 * @method Opsu2   setTelefono()           Sets the current record's "telefono" value
 * @method Opsu2   setCorreo()             Sets the current record's "correo" value
 * @method Opsu2   setEstadoId()           Sets the current record's "estado_id" value
 * @method Opsu2   setPnfId()              Sets the current record's "pnf_id" value
 * @method Opsu2   setTransferir()         Sets the current record's "transferir" value
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOpsu2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('opsu2');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('nombre_universidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nucleo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('carrera', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_rusnies', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nacionalidad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('identificacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('nombres', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('rama', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('anio_graduacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ia', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('semestre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('correo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('pnf_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('transferir', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}