<?php
// This a cache config file for the sfTCPDFPlugin 
//
// auto-generated by sfTCPDFPluginConfigHandler
// date: 2018/07/24 21:38:05
return array (
  'default' => 
  array (
    'K_TCPDF_EXTERNAL_CONFIG' => true,
    'K_PATH_MAIN' => NULL,
    'K_PATH_URL' => NULL,
    'K_PATH_FONTS' => NULL,
    'K_PATH_CACHE' => NULL,
    'K_PATH_URL_CACHE' => NULL,
    'K_PATH_IMAGES' => NULL,
    'K_BLANK_IMAGE' => NULL,
    'PDF_PAGE_FORMAT' => 'Letter',
    'PDF_PAGE_ORIENTATION' => 'P',
    'PDF_CREATOR' => 'TCPDF',
    'PDF_AUTHOR' => 'TCPDF',
    'PDF_HEADER_TITLE' => 'TCPDF Example',
    'PDF_HEADER_STRING' => 'by Nicola Asuni - Tecnick.com
www.tcpdf.org - symfony1 plugin by Vernet Loïc (Aka COil) - http://www.symfony-project.org/plugins/sfTCPDFPlugin',
    'PDF_HEADER_LOGO' => 'tcpdf_logo.jpg',
    'PDF_HEADER_LOGO_WIDTH' => 30,
    'PDF_UNIT' => 'mm',
    'PDF_MARGIN_HEADER' => '5',
    'PDF_MARGIN_FOOTER' => '10',
    'PDF_MARGIN_TOP' => '27',
    'PDF_MARGIN_BOTTOM' => '25',
    'PDF_MARGIN_LEFT' => '15',
    'PDF_MARGIN_RIGHT' => '15',
    'PDF_FONT_NAME_MAIN' => 'helvetica',
    'PDF_FONT_SIZE_MAIN' => '10',
    'PDF_FONT_NAME_DATA' => 'helvetica',
    'PDF_FONT_SIZE_DATA' => '8',
    'PDF_FONT_MONOSPACED' => 'courier',
    'PDF_IMAGE_SCALE_RATIO' => '4',
    'HEAD_MAGNIFICATION' => '1.1',
    'K_CELL_HEIGHT_RATIO' => '1.25',
    'K_TITLE_MAGNIFICATION' => '1.3',
    'K_SMALL_RATIO' => '2/3',
    'K_THAI_TOPCHARS' => true,
    'K_TCPDF_CALLS_IN_HTML' => true,
  ),
  'my_config' => 
  array (
    'K_TCPDF_EXTERNAL_CONFIG' => true,
    'K_PATH_MAIN' => '/var/www/ucs_control/plugins/sfTCPDFPlugin/tcpdf/',
    'K_PATH_URL' => 'http://localhost/',
    'K_PATH_FONTS' => '/var/www/ucs_control/plugins/sfTCPDFPlugin/tcpdf/fonts',
    'K_PATH_CACHE' => '/var/www/ucs_control/plugins/sfTCPDFPlugin/tcpdf/cache',
    'K_PATH_URL_CACHE' => 'http://localhost/cache',
    'K_PATH_IMAGES' => '/var/www/ucs_control/plugins/sfTCPDFPlugin/tcpdf/images',
    'K_BLANK_IMAGE' => '/var/www/ucs_control/plugins/sfTCPDFPlugin/tcpdf/images/_blank.png',
  ),
);
//
