<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/07/24 21:35:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=sige',
  'username' => 'postgres',
  'password' => 'post321gres',
  'name' => 'doctrine',
)),);
