<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/07/30 15:21:01
sfConfig::add(array(
  'mod_preinscripcion_enabled' => true,
  'mod_preinscripcion_view_class' => 'sfPHP',
));
