<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/04/26 15:10:16
sfConfig::add(array(
  'mod_preinscripcion_enabled' => true,
  'mod_preinscripcion_view_class' => 'sfPHP',
));
