<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/04/26 15:39:58
sfConfig::add(array(
  'mod_sfdependentselectauto_enabled' => true,
  'mod_sfdependentselectauto_view_class' => 'sfPHP',
));
