<?php

/**
 * ____UBV_NOTASTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ____UBV_NOTASTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ____UBV_NOTASTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('____UBV_NOTAS');
    }
}