<?php

/**
 * ActualizarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActualizarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActualizarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Actualizar');
    }
}