<?php

/**
 * ElamNotasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElamNotasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElamNotasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElamNotas');
    }
}