<?php

/**
 * ElectivosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElectivosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElectivosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Electivos');
    }
}