<?php

/**
 * EstudianteMmcEstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstudianteMmcEstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstudianteMmcEstadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstudianteMmcEstado');
    }
}