<?php

/**
 * Graduados2019Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Graduados2019Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Graduados2019Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Graduados2019');
    }
}