<?php

/**
 * Graduados2019Cta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Graduados2019Cta extends BaseGraduados2019Cta
{

}