<?php

/**
 * Graduados9Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Graduados9Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Graduados9Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Graduados9');
    }
}