<?php

/**
 * Graduandos8Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Graduandos8Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Graduandos8Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Graduandos8');
    }
}