<?php

/**
 * Graduados2019CtaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Graduados2019CtaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Graduados2019CtaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Graduados2019Cta');
    }
}