<?php

/**
 * IndiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IndiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IndiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Indice');
    }
}