<?php

/**
 * MinimosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MinimosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MinimosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Minimos');
    }
}