<?php

/**
 * MmciiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MmciiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MmciiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mmcii');
    }
}