<?php

/**
 * NotasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Notas');
    }
}