<?php

/**
 * Notas9CohoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Notas9CohoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Notas9CohoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Notas9Coho');
    }
}