<?php

/**
 * NotasNacionalesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotasNacionalesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotasNacionalesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotasNacionales');
    }
}