<?php

/**
 * Notas9Coho
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Notas9Coho extends BaseNotas9Coho
{

}