<?php

/**
 * Nuevoingreso2018Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Nuevoingreso2018Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Nuevoingreso2018Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Nuevoingreso2018');
    }
}