<?php

/**
 * Opsu2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Opsu2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Opsu2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Opsu2');
    }
}