<?php

/**
 * PnfPreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PnfPreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PnfPreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PnfPre');
    }
}