<?php

/**
 * PreinscripcionCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    preinscripcion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PreinscripcionCurso extends BasePreinscripcionCurso
{
public function save(Doctrine_Connection $conn = null)
    {

        $pnfPre = PreinscripcionCursoTable::getPnfPre($this->getPnfPreId());
        $pnf_id=$pnfPre[0]['pnf_id'];
        $this->setPnfId($pnf_id);
        return parent::save($conn);
    }
}