<?php

/**
 * PreinscripcionCursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreinscripcionCursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreinscripcionCursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PreinscripcionCurso');
    }
    public static function getPre($tipo,$identificacion){
            $sql = "SELECT a.*,b.descripcion as pais_origen,c.descripcion as estado,d.descripcion as municipio, e.descripcion as parroquia,
                f.descripcion as pnf
                FROM preinscripcion_curso a
                left join pais_origen b on a.pais_origen_id=b.id
                left join estado c on a.estado_id=c.id
                left join municipio d on a.municipio_id=d.id
                left join parroquia e on a.parroquia_id=e.id
                left join pnf f on a.pnf_id=f.id
                WHERE nacionalidad='$tipo'
                AND identificacion='$identificacion'";
            
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
    public static function getTotalPnf(){
        $sql = "select b.descripcion,count(1)as total  from preinscripcion_curso a 
                left join pnf b on a.pnf_id=b.id
                group by b.descripcion";
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
    public static function getTotalPnfEstado(){
        $sql = "select c.descripcion as estado,b.descripcion as pnf,count(1)as total  from preinscripcion_curso a 
                left join pnf b on a.pnf_id=b.id
                left join estado c on a.estado_id=c.id
                group by c.descripcion,b.descripcion
                order by 1,2";
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
    public static function getPnfPre($id){
        $sql="select * from pnf_pre where id=$id";
        $q = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
}