<?php

/**
 * ReclamoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReclamoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReclamoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reclamo');
    }
}