<?php

/**
 * UnidadCurricularTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadCurricularTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadCurricularTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnidadCurricular');
    }
}