<?php

/**
 * Usuarios2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Usuarios2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Usuarios2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuarios2');
    }
     public static function buscaUsuario($usuario,$clave){
        // $clave=upper(md5('$clave'));
        $sql="SELECT *
              FROM usuarios2
              WHERE usuario = '$usuario' and clave=upper(md5('$clave'))";
        $q=Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc($sql);
        return $q;
    }
}