generator:
  class: sfDoctrineGenerator
  param:
    model_class:           preinscripcion
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          preinscripcion
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          identificacion: {label: Número de Identificación}
          pnombre: {label: Primer Nombre}
          snombre: {label: Segundo Nombre}
          papellido: {label: Primer apellido}
          sapellido: {label: Segundo apellido}
          genero: {label: Género}
          direccion: {label: Dirección}
          fnac: {label: Fecha de nacimiento}
          titulo: {label: Título de pregrado}
          pais_origen_id: {label: País Origen}
          telefono: {label: Teléfono}
          mgi: {label: Realizó la especialización en MGI?}
          otra: {label: Realizó otra especialización?}
          uni_mgi: {label: Indique el nombre de la universidad que acreditó el MGI.}
          uni_pre: {label: Indique el nombre de la universidad que acreditó el Pregrado.}
          uni_otra: {label: Indique la especialidad y el nombre de la universidad donde cursó el Postgrado}
          art_8: {label: Cumplió con el artículo 8?}
          pnfa_id: {label: Seleccione el PNFA que aspira cursar}
          ano_pre: {label: Indique el año de egreso de pregrado}
          ano_mgi: {label: Indique el año de egreso de MGI}
          ano_otra: {label: Indique el año de egreso de la epecialización}
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     
          title: Matrícula de Aspirantes
          actions:
               _save:
